name: Deploy Application WBio
#Deploy
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
  
            - name: Aplicação WBio
              uses: actions/setup-node@v3
              with:
                node-version: 22
                cache: 'npm'
                cache-dependency-path: package-lock.json
            - name: Install dependencies
              run: npm install
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t brunotavaresssssasasasas/aws-docker .
            - name: Push image docker
              run: docker push brunotavaresssssasasasas/aws-docker
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull brunotavaresssssasasasas/aws-docker
            - name: Remove docker container
              run: docker rm -f aws-docker
            - name: Run docker container
              run: docker run -d -p 8000:8000 --name aws-docker brunotavaresssssasasasas/aws-docker
